### ISSUE TITLE
Question about the reported result on FSC147

### ISSUE THREAD

**Issue by donggoing** [IDEA-Research/T-Rex#1]
Thanks for your great work. 
I would like to ask if the evaluation results on FSC147 shown in the report are the models trained on the FSC147 dataset? And the model structure is not going to be published?

**Comment by Mountchicken** [comment]
Hi @donggoing 
T-Rex was not trained on FSC147 since T-Rex is a detection-based model and FSC147 does not have detection annotations. As for the model structure, we do not have plan to publish it yet.
