### ISSUE TITLE
CA-44 Benchmark

### ISSUE THREAD

**Issue by lauesa** [IDEA-Research/T-Rex#10]
Where can the CA-44 Benchmark be found?

**Comment by Mountchicken** [comment]
Hi @lauesa 
We will provide CA-44 asap

**Comment by donggoing** [comment]
Hi @Mountchicken, Could you please give us a specific time to provide CA-44 data set？

**Comment by Mountchicken** [comment]
Will be done by this weekend

**Comment by Mountchicken** [comment]
@donggoing @lauesa 
It's now available at https://github.com/IDEA-Research/T-Rex/blob/master/CA44_Benchmark/README.md
