### ISSUE TITLE
Please also check our work

### ISSUE THREAD

**Issue by hmchuong** [IDEA-Research/T-Rex#12]
Hi,

Thanks for your interesting project. We published a similar paper for class-agnostic similar object finding: https://simpson-cvpr23.github.io/

Please consider citing our work.

Best,

**Comment by ashutoshbk** [comment]
Nice paper, are you planing to open source your code?

**Comment by Mountchicken** [comment]
Hi @hmchuong 
Interesting work, we will cite your paper when we publish a more detailed version of T-Rex.
