### ISSUE TITLE
.tif support and exporting the results

### ISSUE THREAD

**Issue by narges-tk** [IDEA-Research/T-Rex#14]
Very nice work!
I wonder if you could add .tif support as well as an option for exporting the results. Thanks in advance.

**Comment by Mountchicken** [comment]
Hi @narges-tk 
Thanks for your interest in our work. I apologize that my front-end colleagues may not have plans to support other image upload formats. As for returning labeled results, you can refer to this https://github.com/IDEA-Research/T-Rex/issues/4#issuecomment-1831361988
