### ISSUE TITLE
could provide pretrained model for research?

### ISSUE THREAD

**Issue by golfr32** [IDEA-Research/T-Rex#16]
could provide pretrained model for research?

**Comment by Mountchicken** [comment]
Hi @golfr32 
Currently we don't have plan to do this. We are working on a new version of T-Rex and we will release details and model for the new version.

**Comment by golfr32** [comment]
Many thanks for that, when will the new version will be released?

**Comment by Mountchicken** [comment]
Hopefully, within three months

**Comment by golfr32** [comment]
Hi Mountchicken,

Happy new year, hopefully, you are getting well.

Does T-Rex have a plan to release codes and a pre-trained model for research? I am working on counting flowers on a plant with a high-density ratio, there were over 200+ flowers on a small plant on a 0.5 square meter.  Some of them are overlap together, not 100% overlap, from 10% to 90%.  Could we collaborative together for improvement of the model?

**Comment by Mountchicken** [comment]
HI @golfr32 
We don't have the plan to release the model yet. You can try our demo at [here](https://deepdataspace.com/playground/ivp) to see if T-Rex can solve your promblem.
