### ISSUE TITLE
Release the inference code and pre-trained models

### ISSUE THREAD

**Issue by khiemledev** [IDEA-Research/T-Rex#17]
First of all, congrats on your great work!
I'm very interested in appling your work into few-shot data labeling, it'll help a lot in reducing annotation cost. I hope that you can release the inference code and pre-trained models.
Again, great work!

**Comment by Mountchicken** [comment]
Hi @khiemledev 
Currently we don't have plan to release the code. We are working on a better version of T-Rex and we will release details and model for the new version.

**Comment by khiemledev** [comment]
Hi @Mountchicken , I was glad to here that. Then, I'll close this issue, you can announce the code release for the new version on this issue later.
