### ISSUE TITLE
The release of code

### ISSUE THREAD

**Issue by JerExJs** [IDEA-Research/T-Rex#18]
Thanks for your impressive work，When do you expect to release the code？

**Comment by Mountchicken** [comment]
Hi @JerExJs 
Currently we don't have plan to release the code. We are working on a better version of T-Rex and we will release details and model for the new version. Hopefully, we will get it done within three months.

**Comment by Thedatababbler** [comment]
I've tried the demo and its amazing. I just wonder what base-model you choose to train with? GroundedDINO?

**Comment by guoqi1217** [comment]
need you.this project is pretty well

**Comment by monkeycc** [comment]
Hello, will code and models be released soon
@Mountchicken

**Comment by McQQW** [comment]
@monkeycc  Perfect Profile, I like it~

**Comment by Mountchicken** [comment]
T-Rex2 is now available through API

**Comment by monkeycc** [comment]
不开源 
只提供API 
所有图片要上传到你们服务器

这个框架就没什么意思了
