### ISSUE TITLE
Could you show me two test samples in FSC147?

### ISSUE THREAD

**Issue by Hzzone** [IDEA-Research/T-Rex#21]
<img width="917" alt="image" src="https://github.com/IDEA-Research/T-Rex/assets/19267349/e2419d36-871a-475f-8cb7-5823a954f5fe">

<img width="877" alt="image" src="https://github.com/IDEA-Research/T-Rex/assets/19267349/dca0577c-9e2d-46f7-b618-a4f03b4fcaa7">

1121.jpg and 7621.jpg are dominant in the final MAE of FSC-147 dataset. For example, there is a gap of MAE=3000/1190 without '1123.jpg'. I cannot achieve a good result using your demo.

**Comment by Mountchicken** [comment]
Hi @Hzzone 
Sry for the late reply. I tried these two images and T-Rex indeed performs bad. Here is the reason: both two images have objects that are far more than the maximun number(900) that T-Rex can detect. Below, I set the score threshold to 0. and T-Rex can detect 900 boxes, which is still far not enough.
![image (5)](https://github.com/IDEA-Research/T-Rex/assets/65173622/5ab35748-c642-4f3c-89a7-22a05400cc73)
