### ISSUE TITLE
About demo for T-Rex2

### ISSUE THREAD

**Issue by Yutong-Zhou-cv** [IDEA-Research/T-Rex#24]
Thanks for your great contribution! 
I tried sample images on the T-Rex2 model, it works well. However, when I upload images, T-Rex2 cannot detect anything, even just one object (Please refer to the attached image)
![image (6)](https://github.com/IDEA-Research/T-Rex/assets/64592772/b35cf1f7-96cc-4724-992c-405e6f9fc727)
Could you please confirm this matter? Or are there any tips I should pay more attention to?
Thank you for your support in advance:)

**Comment by Mountchicken** [comment]
Hi @Yutong-Zhou-cv 
I tried this image with a screenshot. It's working fine. (a false detection, probably due to the low resolution)
![24621711102477_ pic](https://github.com/IDEA-Research/T-Rex/assets/65173622/a74c2c88-1ac4-4c1c-a926-ec7354ff0f75)

**Comment by Yutong-Zhou-cv** [comment]
@Mountchicken Thanks for your kind reply. I tried again but it still didn't work. There may be some problems on my side and I will use API instead.
Congratulations on your contributions again. Have a nice weekend!
