### ISSUE TITLE
请问这个模型适合这种文档分类检测的任务吗？

### ISSUE THREAD

**Issue by yangfa-zhang** [IDEA-Research/T-Rex#25]
![Weixin Image_20240323221803](https://github.com/IDEA-Research/T-Rex/assets/118345785/a61c3180-c281-463c-a10e-ff64a639a712)

**Comment by Mountchicken** [comment]
Hi @yangfa-zhang 
T-Rex2 might not be good at this task, since it's not trained on document data.
