### ISSUE TITLE
Textual Prompting examples

### ISSUE THREAD

**Issue by antoan** [IDEA-Research/T-Rex#26]
Thank you for making this available.

Is it possible to textually prompt the model, I could not find any examples in the API docs or find a way to do it in the online demo?

Cheers

**Comment by Mountchicken** [comment]
HI @antoan 
Thanks for your interest in our work. The text prompt is not available at this time, as we found its performance to be less impressive than the visual prompt. We are working on optimizing the text prompt and hope to see you soon.

**Comment by Mountchicken** [comment]
I'll close this issue now. Feel free to re-open it.
