### ISSUE TITLE
ImportError: cannot import name 'BatchPointInfer' from 'dds_cloudapi_sdk'

### ISSUE THREAD

**Issue by taoxunqiang** [IDEA-Research/T-Rex#27]
Thank you for your wonderful work.

I installed the trex according to "Setup". 
The following error occurred when running "from dds_cloudapi_sdk import BatchRectInfer, BatchPointInfer, BatchEmbdInfer"：
ImportError: cannot import name 'BatchPointInfer' from 'dds_cloudapi_sdk' (/home/nvidia/miniconda3/envs/demo/lib/python3.8/site-packages/dds_cloudapi_sdk/__init__.py)

How can I fix it?

Thank you.

**Comment by Mountchicken** [comment]
Hi @taoxunqiang 
Make sure you have installed the latest version of dds API:
```bash
pip install dds-cloudapi-sdk==0.1.1
```

**Comment by Mountchicken** [comment]
I'll close this issue now. Feel free to re-open it.
