### ISSUE TITLE
API

### ISSUE THREAD

**Issue by yu9s** [IDEA-Research/T-Rex#29]
Dear author:
       I have applied for an API.  May I ask how long it will take to receive a response

**Comment by Mountchicken** [comment]
Hi @yu9s 
We are currently manually distributing tokens, and there might be omissions. Please submit another application

**Comment by yu9s** [comment]
> Hi @yu9s We are currently manually distributing tokens, and there might be omissions. Please submit another application

Thank you for your reply， Maybe I need to be patient and wait,  because I sent the email at 2 pm in the afternoon

**Comment by Mountchicken** [comment]
I'll close this issue now. Feel free to re-open it.

**Comment by hongge831** [comment]
@Mountchicken Hi， I also sent a api application mail, how long it will be took ？
