### ISSUE TITLE
Online Gradio demo is error

### ISSUE THREAD

**Issue by tongchangD** [IDEA-Research/T-Rex#32]
Online Gradio demo is error, please check it,thanks.

best wish

tongchangD

**Comment by Mountchicken** [comment]
Hi @tongchangD 
Thanks for reporting. Can you describe more about the error? It's working fine on myside

**Comment by tongchangD** [comment]
@Mountchicken  
like this

![image](https://github.com/IDEA-Research/T-Rex/assets/36293393/80bebc31-9dfa-4089-b9c2-93ab957b4c90)

**Comment by tongchangD** [comment]
sorry , it can run. 
![image](https://github.com/IDEA-Research/T-Rex/assets/36293393/90cf6e9f-190c-4a68-b584-140b5cdadeac)
