### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [IDEA-Research/T-Rex#33]
Hi,
Thanks for releasing this great work! Might it be possible to switch to an open source license?
Thank you!

**Comment by Mountchicken** [comment]
Hi @fakerybakery 
Thanks for your interest in our work. This license is used according to the company's rules, so I can't make any modifications. But feel free to this work for research purposes.

**Comment by fakerybakery** [comment]
Thanks for your reply! Makes sense. Thank you for releasing this amazing work!
