### ISSUE TITLE
Question about CA44 results

### ISSUE THREAD

**Issue by wjn922** [IDEA-Research/T-Rex#34]
Hi, congratulate for the wonder projects of T-Rex and T-Rex2!

I'd like to know whether the results for CA44 in paper T-Rex were reported on the valid set or the test set? Besides, do you have the specific results for Figure 7 (the values of MAE and NMAE in CA44)? Many thanks!

**Comment by Mountchicken** [comment]
Hi @wjn922 
We are evaluating on train, val, and test sets. All datasets in this [config](https://github.com/IDEA-Research/T-Rex/blob/master/CA44_Benchmark/ca44_config.py) are used for evaluation. The specific results can be find at [here](https://github.com/IDEA-Research/T-Rex/blob/master/CA44_Benchmark/result.json).

**Comment by wjn922** [comment]
Thanks for your quick response!

In my understanding, you adopt the CA44 train set for training. And then directly using the model to evaluate on CA44 val/test set, FSC-147 test set, FSCD-LVIS test set. Am I correct? I am curious why you also use the CA44 train set for evaluation?

And after checking the [results](https://github.com/IDEA-Research/T-Rex/blob/master/CA44_Benchmark/result.json), I found that the performance of GroundingDINO is much better than that in the paper T-Rex. What's the reason?

Many thanks in advance.

**Comment by Mountchicken** [comment]
Sorry for the misunderstanding. I found that the Grounding DINO and FamNet results were results for a certain version of T-Rex. I've re-updated the results and they should be correct now. For CA-44 Benchmark, we only use it for evaluation (all train, val, and test sets will be used for evaluation) and we do not train on this benchmark.

**Comment by wjn922** [comment]
Thanks for your reply. Great works again!

**Comment by jerpelhan** [comment]
Hi! I have a question. If CA-44 wasn’t used for training, what dataset was used to train the T-Rex (the counting version)?
