### ISSUE TITLE
what is inference time?

### ISSUE THREAD

**Issue by spacewalk01** [IDEA-Research/T-Rex#38]
Hello, I would like to know about inference time per image. And how many images can it infer at once for free?

**Comment by Mountchicken** [comment]
Hi @spacewalk01 
You can use a batch size of 4 for inference, and here is the inference time.
![image](https://github.com/IDEA-Research/T-Rex/assets/65173622/39a85f3c-6573-4e40-9c41-6ffe8886d173)
