### ISSUE TITLE
How to save annotation information?

### ISSUE THREAD

**Issue by WYL-Projects** [IDEA-Research/T-Rex#4]

**Comment by Mountchicken** [comment]
Hi @WYL-Projects 
This feature is not currently implemented on the front end. But there is a hack way to do it. You can turn on developer mode in your browser (press F12) and after each inference, the network will return the detection results in json format. Boxes are in xyxy format.
![image](https://github.com/IDEA-Research/T-Rex/assets/65173622/d7a8f6ab-ddb9-40ad-ab21-10ce20df32de)
