### ISSUE TITLE
Where is the text prompt for T-Rex2?

### ISSUE THREAD

**Issue by openformer** [IDEA-Research/T-Rex#40]
[T-Rex2: Towards Generic Object Detection via Text-Visual Prompt Synergy](https://arxiv.org/pdf/2403.14610.pdf)
So where is the text prompt for T-Rex2?

**Comment by Mountchicken** [comment]
Hi @openformer 
For now, we do not provide API or demo for the text prompt part.

**Comment by GallonDeng** [comment]
+1

**Comment by openformer** [comment]
> Hi @openformer For now, we do not provide API or demo for the text prompt part.

When will you provide? @Mountchicken

**Comment by Mountchicken** [comment]
Currently, we are not very satisfied with the demo performance of the text prompt, we are working on optimizing it.

**Comment by PatrickLef** [comment]
HI @Mountchicken Any updates on the text prompt? Is it still not working well? I wish to combine text+visual prompt
