### ISSUE TITLE
only one class visual prompt for once

### ISSUE THREAD

**Issue by GallonDeng** [IDEA-Research/T-Rex#41]
for generic visual prompt mode, it only supports one class prompt, right? It is possible to detect different classes simultaneously with multiple prompts for different classes?

**Comment by Mountchicken** [comment]
Hi @AllenDun 
This feature is supported for sure. The essence of multi-category inference is to have a visual prompt embedding for each category. You can use [customize_embedding](https://github.com/IDEA-Research/T-Rex/blob/trex2/trex/model_wrapper.py#L182C9-L182C28) multiple times to customize the embedding for each category. and then use [embedding_inference](https://github.com/IDEA-Research/T-Rex/blob/trex2/trex/model_wrapper.py#L235) for multi-category inference.

**Comment by GallonDeng** [comment]
@Mountchicken thanks for reply. So it is supported when use API, not the online demo

**Comment by Mountchicken** [comment]
Yes
