### ISSUE TITLE
Querying Coordinate Output Capabilities in T-Rex Project Web Demo

### ISSUE THREAD

**Issue by CarrieX6** [IDEA-Research/T-Rex#42]
Hello, I greatly appreciate the work you've put into the T-Rex(2) project; it has been very inspiring to me. I am interested in knowing if it is possible to directly obtain the coordinates of the bounding boxes or the center points when using the web demo for testing. Or, would I need to fork the project and run it on my own to achieve this functionality?

**Comment by Mountchicken** [comment]
Hi @CarrieX6 
Thanks for your interest in our work. In our [Gradio demo](https://huggingface.co/spaces/Mountchicken/T-Rex2), you can get all the bounding box outputs in the coco format:
![25171712038001_ pic](https://github.com/IDEA-Research/T-Rex/assets/65173622/2de7929c-abff-4dd1-8a10-b42bab75b55d)

**Comment by CarrieX6** [comment]
Thank you very much for your response. It has resolved my query.

**Comment by CarrieX6** [comment]
> Hi @CarrieX6 Thanks for your interest in our work. In our [Gradio demo](https://huggingface.co/spaces/Mountchicken/T-Rex2), you can get all the bounding box outputs in the coco format: ![25171712038001_ pic](https://private-user-images.githubusercontent.com/65173622/318661494-2de7929c-abff-4dd1-8a10-b42bab75b55d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTM3MDEsIm5iZiI6MTcxMjExMzQwMSwicGF0aCI6Ii82NTE3MzYyMi8zMTg2NjE0OTQtMmRlNzkyOWMtYWJmZi00ZGQxLThhMTAtYjQyYmFiNzViNTVkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAzMDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYTYwZDRjMDEyODFiN2U0NTMyMDY2NjU4YTQ2NzVkZDc4MzhhYTAwNGIxNzRiYTllOTY5NTc4Y2I0OWYzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l3Yq8cVVdZqpnAeopFM0bfec38wSk1A2-rI46DHYP5A)

---

I have also encountered an issue with outputting specific category detections with a given input (the 'category_id'). It seems that there's no option for outputting appointed categories at [https://huggingface.co/spaces/Mountchicken/T-Rex2](Gradio demo). Is there a solution available in the API for this? Thank you very much for your assistance.

**Comment by Mountchicken** [comment]
For both the Gradio demo and the DDS demo, we do not support multi-category inference for now. However this is available in the API. Check this [example code](https://github.com/IDEA-Research/T-Rex/blob/trex2/demo_examples/interactive_inference.py#L32) for multi-category inference in the interactive visual prompt mode. Check this [comment](https://github.com/IDEA-Research/T-Rex/issues/41#issuecomment-2028028186) for multi-category inference in the generic visual prompt mode.

**Comment by CarrieX6** [comment]
> For both the Gradio demo and the DDS demo, we do not support multi-category inference for now. However this is available in the API. Check this [example code](https://github.com/IDEA-Research/T-Rex/blob/trex2/demo_examples/interactive_inference.py#L32) for multi-category inference in the interactive visual prompt mode. Check this [comment](https://github.com/IDEA-Research/T-Rex/issues/41#issuecomment-2028028186) for multi-category inference in the generic visual prompt mode.

Got it. Thanks a lot for your response. Have a nice day!
