### ISSUE TITLE
Will TRex-1 model file will be provided ?

### ISSUE THREAD

**Issue by SibiK-PIML** [IDEA-Research/T-Rex#43]
As I have being following your work from the beginning with the TRex-1 model, all these work are extremely excellent.  Is it possible to provide the TRex-1 model file, so that further development will be much easier.

**Comment by Mountchicken** [comment]
Hi @SibiK-PIML 
Thank you for your continued attention to our work. We are sorry to say that currently we have no intention of open-sourcing the T-Rex or T-Rex2 models, but feel free to use our API service.
