### ISSUE TITLE
What did you guys open source? Maybe added this on your docs 

### ISSUE THREAD

**Issue by cudanexus** [IDEA-Research/T-Rex#44]
I was very frustrated by seeing this 
People to get popular posing as opensource but actually they are completely private like re-trex 
Hope there will we open trex for everyone

**Comment by Mountchicken** [comment]
We're sorry you're disappointed with our project. To clarify, we didn't claim our entire project was open source. What we've made available is the code to use our API, which is freely accessible.

Although we haven't open-sourced the project itself, we have provided free access to our API to support users from both academia and the industry. We've already helped many users meet their needs through our project.

Regarding the possibility of recreating our project, we encourage you to attempt it. Our comprehensive paper is available to guide you through the process. If you encounter difficulties, we're ready to provide further details to assist you.
