### ISSUE TITLE
Object tracking in video

### ISSUE THREAD

**Issue by rowels-itf** [IDEA-Research/T-Rex#47]
Hi, I have read in a closed topic (https://github.com/IDEA-Research/T-Rex/issues/19#issuecomment-2012381036) that T-Rex 2 can be applied to videos too, but I don't see how in your demo. Could you please explain how to do that?

Additionally, do you have any suggestions on how to use your excellent object detection for object tracking? Could you suggest a package for object tracking maybe using your COCO results on the first frame as input? Thank you!

**Comment by Mountchicken** [comment]
Hi @rowels-itf 
We will soon provide a demo for video object detection and tracking. Technically, we will use T-Rex2 to detect each frame and get the result bounding boxes. Then we will use ByteTrack to track them.
