### ISSUE TITLE
跑偏了。

### ISSUE THREAD

**Issue by xiyangyang99** [IDEA-Research/T-Rex#48]
groundingdino和本文类似，但是在工程运用上，不好落地，推理速度不像yolo-world那般快。transformer不好加速推理。跨模态方式的文本加载方式在加速上处理较为麻烦。

**Comment by Mountchicken** [comment]
Hi @xiyangyang99 
Indeed, DETR-based models face significant deployment and speed challenges, and we are trying to optimize them. Yet from the perspective of open-set detection performance, both GroundingDINO and T-Rex deliver remarkably better results.

**Comment by Artificial-Inability** [comment]
> groundingdino和本文类似，但是在工程运用上，不好落地，推理速度不像yolo-world那般快。transformer不好加速推理。跨模态方式的文本加载方式在加速上处理较为麻烦。

 神逻辑，在我的小方向上不好用 = 这算法跑偏了，别人做的东西你直接拿过来就好用你自己的价值在哪？一点建设性没有的issue赶紧关了吧，不嫌丢人吗99年的喜羊羊同学？ @xiyangyang99

**Comment by chooooock** [comment]
> groundingdino和本文类似，但是在工程运用上，不好落地，推理速度不像yolo-world那般快。transformer不好加速推理。跨模态方式的文本加载方式在加速上处理较为麻烦。

在部署Gdino到trt框架的时候遇到问题，在很多project的issues上看到你的回到，方面分享一下Gdino到onnx再到trt的可行方法吗？或者留个联系方式可以吗？
