### ISSUE TITLE
K set of InfoNCE Loss at Region-Level Contrastive Alignment

### ISSUE THREAD

**Issue by urbaneman** [IDEA-Research/T-Rex#50]
What do you set K in L_algin?
<img width="527" alt="image" src="https://github.com/IDEA-Research/T-Rex/assets/34812886/a2a16926-fcb3-4cb7-bc7f-0f9f51d642fe">

Visual Prompts only choose once of every different categories? Is this correct?

**Comment by Mountchicken** [comment]
Hi @urbaneman 
K is the number of categories in each image. Given an image with three categories A, B, and C, then we will extract three visual prompt embeddings for each category.

**Comment by urbaneman** [comment]
I got. As I understand it. 
This paper seems to have a very large workload.
THANKS for your great work.

**Comment by lyf6** [comment]
when there is multiple gt bboxs for each category, select one randomly?

**Comment by Mountchicken** [comment]
@lyf6 
For each category, we will randomly select 1 to N gt boxes as visual prompts. N = len(boxes)

**Comment by lyf6** [comment]
thank you for your reply. when select 1 to N gt boxes as visual prompts, the infonce loss will be different from your paper version?
