### ISSUE TITLE
Testing on the Videos?

### ISSUE THREAD

**Issue by DaneshShokri94** [IDEA-Research/T-Rex#55]
Thanks for this amayzing algorithm
My questoin is how can we test and run T-Rex2 on the vidoes?

**Comment by Mountchicken** [comment]
Hi @DaneshShokri94 
Feel free to try our video demo at https://deepdataspace.com/playground/ivp_video

**Comment by DaneshShokri94** [comment]
Thanks @Mountchicken 
It was nice
Good job
