### ISSUE TITLE
About the T-Rex / T-Rex2 demo

### ISSUE THREAD

**Issue by hengseuer** [IDEA-Research/T-Rex#56]
It is amazing work!

In the model of demo, did you use more data than mentioned in the paper, such as counting related dataset ?

**Comment by Mountchicken** [comment]
Hi @hengseuer 
Thanks for your interest in our work. Our online demo uses additional data for training. For example, we added a lot of data for intensive scenarios, e.g. counting related data.

**Comment by hengseuer** [comment]
Thanks for your reply.

Can you give an overview of the counting-related datasets used in the online demo?

**Comment by jetyingjia** [comment]
+1

**Comment by Mountchicken** [comment]
Datasets with dense annotation are all suitable. For example, FSCD dataset at https://github.com/VinAIResearch/Counting-DETR

**Comment by hengseuer** [comment]
Thanks a lot.

**Comment by fuweifuvtoo** [comment]
M
