### ISSUE TITLE
Access to T-REX2

### ISSUE THREAD

**Issue by almak75** [IDEA-Research/T-Rex#60]
I played with your T-REX2 API. I really liked it. But I've already used the API limit.
I read that you do not plan to publish the model. Please tell us about how we can use the model in real projects? If you plan to provide access to the API for money, I would like to know the tariffs and conditions.

**Comment by Mountchicken** [comment]
We are preparing to launch our API's paid service. Currently, we can offer you additional API quota for free. Please provide us with your email address.

**Comment by Mountchicken** [comment]
We are preparing to launch our API's paid service. Currently, we can offer you additional API quota for free. Please provide us with your email address.

**Comment by patrontheo** [comment]
@Mountchicken Are you planning to open source the weights of the T-REX2 model ?
I also have the same question regarding GroundingDINO 1.5 Pro.
Thanks for the strong work!

**Comment by Mountchicken** [comment]
Hi @patrontheo 
We don't have plan to open source both models.
