### ISSUE TITLE
interactive_inference.py and gradio demo not working

### ISSUE THREAD

**Issue by benjamin32561** [IDEA-Research/T-Rex#64]
I am trying to use both the interactive_inference.py and gradio demo to understand the API and how to use it for generic visual prompt but both return and error
![Opera Snapshot_2024-06-04_092410_huggingface co](https://github.com/IDEA-Research/T-Rex/assets/62675494/38601035-0381-4a90-9b54-873cce3730c0)
![Opera Snapshot_2024-06-04_092419_huggingface co](https://github.com/IDEA-Research/T-Rex/assets/62675494/08566d97-2132-4347-9c8d-daadec4616ca)

**Comment by Mountchicken** [comment]
Hi @benjamin32561 
The Gradio demo hosted on HuggingFace is deprecated. You can try online demo here: https://deepdataspace.com/playground/ivp

**Comment by benjamin32561** [comment]
thank you, I resolved the error I had with running locally too, thanks
