### ISSUE TITLE
ReadTimeout Error when using TRex2APIWrapper

### ISSUE THREAD

**Issue by benjamin32561** [IDEA-Research/T-Rex#65]
I run some code using the TRex2APIWrapper and I get this error:
ReadTimeout: HTTPSConnectionPool(host='api.deepdataspace.com', port=443): Read timed out. (read timeout=2)

funny thing is it worked ten minutes ago
connecting to a different WiFi network resolved it
how can I make sure it does not happen again?

**Comment by Mountchicken** [comment]
Hi @benjamin32561 
This happens occasionally, and we are continually optimizing our backend administration, and currently don't have a good solution for it

**Comment by benjamin32561** [comment]
Ok, thanks anyway!
