### ISSUE TITLE
Extended API Access and Payment Options for T-Rex 2

### ISSUE THREAD

**Issue by benjamin32561** [IDEA-Research/T-Rex#67]
I am using the T-Rex 2 API but I need more request then what is given in the free trial, what can I do?
Willing to pay for the service.

**Comment by Mountchicken** [comment]
Hi @benjamin32561 
Thanks for your interest in our work. If you need more API token, you can fill out this form https://docs.google.com/forms/d/e/1FAIpQLSfjogAtkgoVyFX9wvCAE15mD7QtHdKdKOrVmcE5GT1xu-03Aw/viewform
