### ISSUE TITLE
How to Set Vision Prompt Image and Target Image Using API

### ISSUE THREAD

**Issue by wangnan2021** [IDEA-Research/T-Rex#68]
In the provided online demo, the vision prompt image and the image to be detected can be two different images. By giving a prompt on the vision prompt image, you can then detect it on the other image. How can this functionality be implemented in the API?
![image](https://github.com/IDEA-Research/T-Rex/assets/80313369/fe6cc808-7e3d-4363-9a95-7eccce5fb603)

**Comment by Mountchicken** [comment]
Hi @wangnan2021 
This function can be called through generic inference API. See example here: https://github.com/IDEA-Research/T-Rex/blob/trex2/demo_examples/generic_inference.py

**Comment by wangnan2021** [comment]
Thank you for your response.
Could you please confirm if T-Rex2 is unable to output instance masks? If so, is it possible to use the API to call T-Rex1 instead?

**Comment by Mountchicken** [comment]
Hi @wangnan2021 
T-Rex2 doesn't support mask output. You need to use an additional interactive segmentation model like SAM to get masks, same for T-Rex1
