### ISSUE TITLE
About the learning rate in the training process

### ISSUE THREAD

**Issue by fuweifuvtoo** [IDEA-Research/T-Rex#69]
From your reply, I know that: T-rex2 first trains the text prompts and then trains both the text and visual prompts in successive iterations;

So when training text and visual prompts in successive iterations, do the text prompt encoder and decoder use a smaller learning rate, while the visual prompts encoder uses a larger learning rate?

If so, is there a specific value?

**Comment by Mountchicken** [comment]
The learning rate is the same in every stage
