### ISSUE TITLE
Release code

### ISSUE THREAD

**Issue by dacquaviva** [IDEA-Research/T-Rex#7]
Hello 

Congrats, really impressed with your work. 

I wanted to ask, is there any plan to release the code and model?

Thanks

**Comment by Mountchicken** [comment]
Hi @dacquaviva 
Thanks for your interest in our project. T-Rex is still in early beta and we have no plans to open source it for now. We will continue to optimize the performance of T-Rex, and look forward to seeing a more developed T-Rex with you!

**Comment by yang-fei** [comment]
> Hi @dacquaviva Thanks for your interest in our project. T-Rex is still in early beta and we have no plans to open source it for now. We will continue to optimize the performance of T-Rex, and look forward to seeing a more developed T-Rex with you!

do you have plan to release the code in the future, just like SAM?

**Comment by Mountchicken** [comment]
We may open source in the future, but have no plans to do so recently
