### ISSUE TITLE
The interactive visual prompt yielded unsatisfactory results.

### ISSUE THREAD

**Issue by wangjl1993** [IDEA-Research/T-Rex#71]
![image](https://github.com/IDEA-Research/T-Rex/assets/8839139/f2a13380-3589-48d0-8921-f8b507c5e4b2)

Is this a bug? always return the wrong boxes.

**Comment by wangjl1993** [comment]
I found that "generic visual prompt" is better than "interactive visual prompt".  
![image](https://github.com/IDEA-Research/T-Rex/assets/8839139/09e91335-54dd-4b3a-af50-d6c9c66c69d8)
![image](https://github.com/IDEA-Research/T-Rex/assets/8839139/308fe52c-340d-4ffa-9b14-631af963d229)

**Comment by Mountchicken** [comment]
Hi @wangjl1993 
The interactive visual prompt is for the case that the prompt image and target image are the same. When they are not, using generic visual prompt.

**Comment by wangjl1993** [comment]
> Hi @wangjl1993 The interactive visual prompt is for the case that the prompt image and target image are the same. When they are not, using generic visual prompt.

OK! thx~

**Comment by fuweifuvtoo** [comment]
When the number of reference image is 1, and the reference image and the target image are different images, is there any difference between interactive visual prompt and generic visual prompt? 
I think in this case, IVP == GVP?
