### ISSUE TITLE
About visual prompt.

### ISSUE THREAD

**Issue by hengseuer** [IDEA-Research/T-Rex#73]
Hi @Mountchicken ,

Suppose the batch size is set to 4.

In the first image, categories A and B have (N1_A) and (N1_B) instances, respectively.
In the second image, categories C and D have (N2_C) and (N2_D) instances, respectively.
In the third image, categories A and B have (N3_A) and (N3_B) instances, respectively.
In the fourth image, categories C and D have (N4_C) and (N4_D) instances, respectively.

For category A in the first image, is its visual prompt selected randomly from 1 to N1, or from 1 to (N1 + N3)? 
If category C is the negative sample category for the first image, is its visual prompt selected randomly from 1 to N2 (N4), or from 1 to (N2 + N4)?

**Comment by Mountchicken** [comment]
Hi @hengseuer 

- For category A in both the first and the third image, its visual prompt is selected randomly from 1 to (N1 + N3)
- In the first image, category C will be the negative prompts, sampled from 1 to (N2 + N4)

**Comment by hengseuer** [comment]
Thanks. Understood.
