### ISSUE TITLE
Can I purchase more tokens to use your API more extensively?

### ISSUE THREAD

**Issue by ashutoshbk** [IDEA-Research/T-Rex#81]

**Comment by Mountchicken** [comment]
You can get more tokens from this form: https://docs.google.com/forms/d/e/1FAIpQLSfjogAtkgoVyFX9wvCAE15mD7QtHdKdKOrVmcE5GT1xu-03Aw/viewform?usp=sf_link

**Comment by ashutoshbk** [comment]
Okay, Thanks
