### ISSUE TITLE
**Request for Offline Use of Project Source Code and Inference Files

### ISSUE THREAD

**Issue by dejun219** [IDEA-Research/T-Rex#86]
Dear author,

I have a question regarding the use of your project. The data I intend to annotate involves geospatial information, which cannot be processed online due to security reasons. Could you please let me know if it's possible to download the project source code and inference files to use them on an offline local machine? 

I look forward to your response and appreciate your assistance. Thank you very much.

**Comment by Mountchicken** [comment]
Hi @dejun219 
I'm sorry that currently we do not provide offline inference code. You can only get access to T-Rex2 through API.

**Comment by dejun219** [comment]
ok，Thanks again
