### ISSUE TITLE
about the zero-shot AP for coco eval in the paper of T-rex2

### ISSUE THREAD

**Issue by MengTanOwn** [IDEA-Research/T-Rex#88]
Dear author, I have a question for you.
What is the AP? Is it AP50, AP75, AP50:AP95, or AP50:AP75?

**Comment by Mountchicken** [comment]
It's mAP or AP50:AP75

**Comment by hao416** [comment]
So it is not the first metric on coco( Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ]) but additional AP50:AP75?

**Comment by hao416** [comment]
> Dear author, I have a question for you. What is the AP? Is it AP50, AP75, AP50:AP95, or AP50:AP75?

Hi, I want to know mAP is Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] on coco? Thanks!

**Comment by Mountchicken** [comment]
Yes

**Comment by hao416** [comment]
> Yes

thanks
